const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
const os = require('node:os');
let browser;
const settle = async page => { await page.waitForTimeout(250); await page.waitForFunction(() => !document.getElementById('choose-folder').disabled); };
const pause = async page => { if ((await page.locator('#play-state').innerText()) === '再生中') await page.click('#stop'); };
(async () => {
  const temp = path.resolve(process.env.PHOTO_MEMORY_TEST_DIR || os.tmpdir());
  const output = path.resolve(process.env.PHOTO_MEMORY_SCREENSHOTS || 'test-results');
  await fs.mkdir(output, {recursive:true});
  browser = await chromium.launchPersistentContext(path.join(temp,'photo-memory-period-'+Date.now()), {headless:true,executablePath:process.env.PLAYWRIGHT_BROWSER_PATH||undefined,viewport:{width:768,height:1024},hasTouch:true,env:{...process.env,TEMP:temp,TMP:temp}});
  await browser.route('**/src/faces.js*', route => route.fulfill({ contentType: 'text/javascript', body: 'export const faceFilter = { check: async()=>true, clear(){} };' }));
  await browser.route('**/src/deployment-config.js*',r=>r.fulfill({contentType:'text/javascript',body:"export const GOOGLE_CLIENT_ID = '';"}));
  const page = await browser.newPage(), errors = [];
  page.on('pageerror',error=>errors.push(error.message));
  const idle=()=>page.waitForFunction(()=>!document.getElementById('choose-folder').disabled);
  const offset=date=>Math.round((Date.UTC(+date.slice(0,4),+date.slice(4,6)-1,+date.slice(6))-Date.UTC(1992,0,1))/86400000);
  const slide=async(bound,date)=>page.locator('#'+bound+'-range').fill(String(offset(date)));
  await page.goto(process.env.PHOTO_MEMORY_URL||'http://localhost:5502');
  await page.waitForSelector('#start-range');
  assert.equal(await page.locator('#start-date').inputValue(),'19920101');
  assert.equal(await page.locator('#end-date').inputValue(),'20501231');
  assert.equal(await page.locator('#end-range').getAttribute('max'),String(offset('20501231')));
  await page.click('#demo');await idle();
  await slide('start','20240403');await slide('end','20240403');
  assert.equal(await page.locator('#start-date-label').innerText(),'2024年4月3日');
  assert.equal(await page.locator('#end-range').getAttribute('aria-valuetext'),'2024年4月3日');
  await settle(page);await idle();
  assert.equal(await page.locator('#viewer-count').innerText(),'1 PHOTOS / 0 VIDEOS');
  assert.equal(await page.locator('#folder-caption').innerText(),'20240403 （春の山歩き）');
  await slide('start','20250815');
  assert.equal(await page.locator('#end-date').inputValue(),'20250815');
  await slide('end','20240403');
  assert.equal(await page.locator('#start-date').inputValue(),'20240403');
  await page.click('#all-dates');
  await page.fill('#start-date','20240229');await page.fill('#end-date','20240301');
  assert.equal(await page.locator('#start-range').inputValue(),String(offset('20240229')));
  await page.locator('#start-range').focus();await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator('#start-date').inputValue(),'20240301');
  await page.fill('#start-date','19911231');await settle(page);
  assert.match(await page.locator('#form-error').innerText(),/1992/);
  await page.fill('#start-date','20230229');await settle(page);
  assert.match(await page.locator('#form-error').innerText(),/実在/);
  await page.click('#all-dates');await settle(page);await idle();
  assert.equal(await page.locator('#viewer-count').innerText(),'8 PHOTOS / 0 VIDEOS');
  const updated=await page.locator('#app-updated').innerText();assert.match(updated,/更新日時：/);assert.match(updated,/\d{2}:\d{2}（日本時間）/);
  await slide('start','20000229');await slide('end','20000301');await settle(page);await idle();
  await page.reload();await page.waitForSelector('#start-range');
  assert.equal(await page.locator('#start-date').inputValue(),'20000229');
  assert.equal(await page.locator('#end-date').inputValue(),'20000301');
  await page.evaluate(()=>localStorage.setItem('photo-memory-viewer.settings.v1',JSON.stringify({start:'19800101',end:'20600101',layout:6,refresh:20})));
  await page.reload();await page.waitForSelector('#start-range');
  assert.equal(await page.locator('#start-date').inputValue(),'19920101');assert.equal(await page.locator('#end-date').inputValue(),'20501231');
  assert.equal(await page.locator('[data-layout="6"]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#refresh').inputValue(),'20');
  for (const width of [768,390]) {
    await page.setViewportSize({width,height:1024});
    await page.locator('#start-range').scrollIntoViewIfNeeded();
    const slider=page.locator('#start-range'),box=await slider.boundingBox();
    assert.ok(box.height>=44 && box.x>=0 && box.x+box.width<=width);
    const before=await slider.inputValue();await slider.tap({position:{x:box.width*(width===768?.6:.25),y:box.height/2}});
    assert.notEqual(await slider.inputValue(),before);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.locator('#date-hint').scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(output,`PhotoMemoryViewer-period-${width}.png`)});
  }
  assert.deepEqual(errors,[]);
  console.log('PASS date sliders: full period, inclusive filtering, crossing, precise input, leap day, validation, persistence, migration, update timestamp and iPad/phone sizing');
  await browser.close();
})().catch(async error=>{console.error(error);await browser?.close();process.exitCode=1;});
